import { test, expect } from "@playwright/test";
import { writeFileSync, mkdirSync } from "node:fs";
import { join } from "node:path";
import ExcelJS from "exceljs";

test("creates a generation and downloads Excel", async ({ page }, testInfo) => {
  await page.goto("/");
  await page.getByText("+ Add additional context").click();
  await page.getByLabel("Project Name").fill("E2E Portal");
  await page.getByLabel("Module/Feature Name").fill("Account creation");
  await page.getByLabel("Acceptance Criteria").fill("Given a user enters valid account details When they submit Then the account is created\nInvalid email shows a validation error");

  const dir = testInfo.outputPath("assets");
  mkdirSync(dir, { recursive: true });
  const screenshot = join(dir, "sample.png");
  writeFileSync(screenshot, Buffer.from("iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8z8BQDwAFgwJ/lb2Z3wAAAABJRU5ErkJggg==", "base64"));
  await page.locator('input[accept="image/png,image/jpeg,image/webp"]').setInputFiles(screenshot);
  await page.getByRole("button", { name: "Generate Test Cases", exact: true }).click();
  await expect(page.getByText(/Verify .*account creation/i).first()).toBeVisible();
  await page.getByRole("button", { name: /Edit/ }).first().click();
  await page.getByLabel("Title").fill("Verify account creation saves the account when the user submits valid account details");
  await page.getByRole("button", { name: /Apply edit/ }).click();
  await page.getByRole("button", { name: "Coverage" }).click();
  await expect(page.getByRole("heading", { name: "Coverage" })).toBeVisible();
  await page.getByRole("button", { name: "Review Test Cases" }).click();
  await page.getByLabel("Area Path").fill("E2E Portal\\General");
  await page.getByLabel("Assigned To").fill("qa@example.com");
  const htmlPage = page.waitForEvent("popup");
  await page.getByRole("button", { name: /Open HTML/ }).click();
  const report = await htmlPage;
  await expect(report.getByText("TestCraft AI Test Case Report")).toBeVisible();
  await report.close();
  const download = page.waitForEvent("download");
  await page.getByRole("button", { name: /Download Azure DevOps Excel/ }).click();
  const file = await download;
  expect(file.suggestedFilename()).toContain("E2E_Portal_General_Azure_DevOps_Test_Cases_");
  const savedPath = testInfo.outputPath(file.suggestedFilename());
  await file.saveAs(savedPath);
  const workbook = new ExcelJS.Workbook();
  await workbook.xlsx.readFile(savedPath);
  const sheet = workbook.getWorksheet("Sheet2")!;
  expect(sheet.getRow(1).values).toEqual([undefined, "ID", "Work Item Type", "Title", "Test Step", "Step Action", "Step Expected", "Area Path", "Assigned To", "State", "Test Type", "AC", "Priority", "Actions"]);
  expect(sheet.getCell("B2").value).toBe("Test Case");
  expect(String(sheet.getCell("C2").value)).toContain("Verify account creation saves the account");
  expect(sheet.getCell("D2").value).toBe("");
  expect(sheet.getCell("E2").value).toBe("");
  expect(sheet.getCell("F2").value).toBe("");
  expect(sheet.getCell("D3").value).toBe(1);
  expect(sheet.getCell("E3").value).toBeTruthy();
  expect(sheet.getCell("F3").value).toBeTruthy();
  expect(sheet.getCell("G2").value).toBe("E2E Portal\\General");
  expect(sheet.getCell("H2").value).toBe("qa@example.com");
  expect(sheet.getCell("I2").value).toBe("Design");
  expect(sheet.getCell("J2").value).toBe("Positive");
  expect(sheet.getCell("K2").value).toBe("AC-001");
  expect(sheet.getCell("L2").value).toBeTruthy();
});
